### ISSUE TITLE
Лабораторна 1 (Redis)

### ISSUE THREAD

**Issue by kuzm1ch** [kuzm1ch/database_labs#2]
перевти текст із російської на українську

**Comment by rexvel** [comment]
Прошу переглянути PR у хронологічному порядку

Гілки мають спільні коміти, які перезатирались, по ідеї мердж-конфліктів від цього не має бути. Є лише один. Скоріше за все він виник від зміни файлової структури репозиторію - просто додав пару папок для структурності:

Як виглядало

```console
```

https://github.com/kuzm1ch/database_labs/pull/6

https://github.com/kuzm1ch/database_labs/pull/7

https://github.com/kuzm1ch/database_labs/pull/8
