### ISSUE TITLE
Лабораторна 1(Redis) - інсталювання 

### ISSUE THREAD

**Issue by kuzm1ch** [kuzm1ch/database_labs#3]
https://andreyex.ru/informaciya/zapusk-redis-v-windows-10  
Перенести мануал по інсталяції в лабораторну. (Не ботрібно повністю все заносити, тілкьи основні моменти)

**Comment by rexvel** [comment]
Додав інформацію для установки WSL.
https://github.com/kuzm1ch/database_labs/pull/5

По докеру І  virtual box WIP

**Comment by kuzm1ch** [comment]
@rexvel  https://github.com/kuzm1ch/database_labs/pull/5  - залиши коменти на TODO 
По докеру І virtual box не потрібно розширювати, двох способів встановлення більш ніж достатньо

**Comment by rexvel** [comment]
Пропоную винести текст з установкою virtual box в окремий файл , а в основному файлі лаби залишити посилання на цей файл і доку докера, просто як альтернативні варіанти для знайомства

**Comment by rexvel** [comment]
Виник також мердж-конфлікт із-за зміни файлової структури наскільки я зрозумів.

**Comment by kuzm1ch** [comment]
task closed with PR
https://github.com/kuzm1ch/database_labs/pull/11

**Comment by kuzm1ch** [comment]
task closed with PR
#11
